image: docker:19.03.6

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
services:
  - docker:19.03.8-dind
stages:
  - push-registry-dev
  - deploy-dev


before_script:
    - docker login -u "phongthien" -p "phongthien"
push-registry-dev:
  stage: push-registry-dev
  script:
    -  docker login -u "phongthien" -p "phongthien"
    - docker build --tag "phongthien/quanlynhahang:latest" -f Dockerfile .
    - docker push "phongthien/quanlynhahang:latest"
  tags:
    - docker
  only:
    - master
deploy-dev:
  image: alpine
  only:
    - master
  stage: deploy-dev
  before_script:
    - apk add sshpass
    - apk add --no-cache openssh-client
    - apk add docker
    - apk add --no-cache rsync
    - '[[ -f /.dockerenv ]]'
    - eval "$(ssh-agent -s)"
  script:
    - sshpass -p "y2D%5]y4Z!Rmc3#Q" ssh -t -oStrictHostKeyChecking=no root@45.32.23.158 'docker login -u "phongthien" -p "phongthien";  docker pull phongthien/quanlynhahang:latest ; docker rm $(docker stop quanlynhahang ); docker run --name quanlynhahang  -d -p 8000:8000 phongthien/quanlynhahang:latest; exit ;'

