"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
# -*- coding: utf-8 -*-s
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kh_qcb-i1jcms=6)#9dqh1%e%cma-^rqt#z^-f3__8()*&gy!n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'src'
]
# REST_FRAMEWORK = {'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(
                "45.32.23.158",
                6379)],
        },
    },
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.routing.application'
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# mysql://b6bf90554358da:567e8bb3@eu-cdbr-west-03.cleardb.net/heroku_cdabdc4c39b1f6a?reconnect=true
DATABASES = {

    # mysql://baa8c17652c072:7a78290d@eu-cdbr-west-03.cleardb.net/heroku_ea7c41c0bb52e0c?reconnect=true
    # b389c51cbab589:1e546445@eu-cdbr-west-03.cleardb.net/heroku_f69c089a84a2606?reconnect=true

    'default': {

        'ENGINE': 'django.db.backends.mysql',
        # MySQL database host ip.
        # MySQL database host ip.
        'HOST': '45.32.23.158',
        # port number.
        'PORT': '3307',
        # database name.
        'NAME': 'quanlynhahang',
        # user name.
        'USER': 'root',
        # password
        'PASSWORD': 'password',
        # connect options
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8',
            'use_unicode': True
            # 'timeout': 20,
        },

    },
    # 'default': {
    #
    #         'ENGINE': 'django.db.backends.mysql',
    #         # MySQL database host ip.
    #         # MySQL database host ip.
    #         'HOST': '127.0.0.1',
    #         # port number.
    #         'PORT': '3306',
    #         # database name.
    #         'NAME': 'quanlynhahang',
    #         # user name.
    #         'USER': 'root',
    #         # password
    #         'PASSWORD': '',
    #         # connect options
    #         'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", 'charset': 'utf8mb4'},
    #
    #     }

}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
CORS_ORIGIN_ALLOW_ALL = True
ALLOWED_HOSTS = ['quanlynhahanguet.herokuapp.com', "localhost"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'
