# Generated by Django 2.2.11 on 2020-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', 'fake_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
