# Generated by Django 2.2.11 on 2020-06-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_billdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('BillDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_chef', to='src.BillDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
