# Generated by Django 2.2.11 on 2020-06-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_chefbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefbill',
            old_name='BillDetail',
            new_name='bill_detail',
        ),
    ]
