# Generated by Django 2.2.11 on 2020-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_bill_total_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbill',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
