# Generated by Django 2.2.11 on 2020-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_chefbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefbill',
            name='delivery_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
