# Generated by Django 2.2.11 on 2020-06-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_chefbill_delivery_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(default='', max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_detail', to='src.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
